version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels: [ ] # prevent the default `dependencies` label from being added to pull requests
    groups:
      simple:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      upgrades:
        applies-to: version-updates
        update-types:
          - "major"
      securityUpdates:
        applies-to: security-updates
        update-types:
          - "minor"
          - "major"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/demo/"
    schedule:
      interval: "monthly"
    labels: [ ] # prevent the default `dependencies` label from being added to pull requests
    groups:
      simple:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      upgrades:
        applies-to: version-updates
        update-types:
          - "major"
      securityUpdates:
        applies-to: security-updates
        update-types:
          - "minor"
          - "major"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/demo/api/ably-token-request"
    schedule:
      interval: "monthly"
    labels: [ ] # prevent the default `dependencies` label from being added to pull requests
    groups:
      simple:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      upgrades:
        applies-to: version-updates
        update-types:
          - "major"
      securityUpdates:
        applies-to: security-updates
        update-types:
          - "minor"
          - "major"
          - "patch"