[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "api"
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[template.environment]
  ABLY_API_KEY = "change me to your Ably API key"
