name: API Reference
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          persist-credentials: false

      - name: Use Node.js 20.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0 # zizmor: ignore[cache-poisoning] no cache input is set, so npm cache is not enabled
        with:
          node-version: 20.x

      - name: Install Package Dependencies
        run: npm ci

      - name: Build Documentation
        run: npm run docs

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        # Only run this step if it's a PR from the main repository, as forks won't have the necessary secrets
        if: github.repository == 'ably/ably-chat-js' && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)) && github.actor != 'dependabot[bot]'
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.ABLY_AWS_ACCOUNT_ID_SDK }}:role/ably-sdk-builds-ably-chat-js
          role-session-name: '${{ github.run_id }}-${{ github.run_number }}'

      - name: Upload Documentation
        uses: ably/sdk-upload-action@4e694297f208b72b5a9f6b1248a1556f19f821d6 # v2.2.0
        # Only run this step if it's a PR from the main repository, as forks won't have the necessary secrets
        if: github.repository == 'ably/ably-chat-js' && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)) && github.actor != 'dependabot[bot]'
        with:
          sourcePath: typedoc/generated
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactName: typedoc
